package Model;
// Generated Nov 30, 2018 9:19:15 AM by Hibernate Tools 5.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Clients generated by hbm2java
 */
public class Clients implements java.io.Serializable {

	private static final long serialVersionUID = 172434504324018254L;
	
	/**
	 * Attributs de la classe correspondant aux champs de la table
	 */
	private ClientsId id;
	private Forfaits forfaits;
	private String typecarte;
	private long numerocarte;
	private Date dateexpiration;
	
	/**
	 * Liste des copies loue par le client
	 */
	private Set<Object> copieses = new HashSet<Object>(0);

	/**
	 * Constructeur par defaut
	 */
	public Clients() 
	{
	}

	/**
	 * Construit un client avec tous ses attributs
	 * @param id : l'id de l'utilisateur correspondant
	 * @param forfaits : le forfait du client
	 * @param typeCarte : le type de carte du client
	 * @param numeroCarte : le numero de carte du client
	 * @param dateExpiration : la date d'expiration de la carte du client
	 */
	public Clients(ClientsId id, Forfaits forfaits, String typeCarte, long numeroCarte, Date dateExpiration)
	{
		this.id = id;
		this.forfaits = forfaits;
		this.typecarte = typeCarte;
		this.numerocarte = numeroCarte;
		this.dateexpiration = dateExpiration;
		
		System.out.println("Nouveau client : " + id.getUtilisateurs().getId().getPrenom());
		System.out.println("Forfait : " + forfaits.getTypeforfait());
		System.out.println("Type carte : " + typeCarte);
		System.out.println("Numero carte : " + numeroCarte);
		System.out.println("Date expi : " + dateExpiration.toString());
	}

	/**
	 * Construit un client avec tous ses attributs et les copies loue
	 * @param id : l'id de l'utilisateur correspondant
	 * @param forfaits : le forfait du client
	 * @param typeCarte : le type de carte du client
	 * @param numeroCarte : le numero de carte du client
	 * @param dateExpiration : la date d'expiration de la carte du client
	 * @param copieses : les copies loue par le client
	 */
	public Clients(ClientsId id, Forfaits forfaits, String typeCarte, long numeroCarte, Date dateExpiration, Set<Object> copies)
	{
		this.id = id;
		this.forfaits = forfaits;
		this.typecarte = typeCarte;
		this.numerocarte = numeroCarte;
		this.dateexpiration = dateExpiration;
		this.copieses = copies;
	}

	/**
	 * Getter de l'id
	 * @return ClientsId id
	 */
	public ClientsId getId()
	{
		return id;
	}

	/**
	 * Setter de l'id
	 * @param id : le nouvel id
	 */
	public void setId(ClientsId id)
	{
		this.id = id;
	}

	/**
	 * Getter du forfait
	 * @return Forfaits forfaits
	 */
	public Forfaits getForfaits() 
	{
		return forfaits;
	}

	/**
	 * Setter du forfait
	 * @param forfaits : le nouveau forfait
	 */
	public void setForfaits(Forfaits forfaits)
	{
		this.forfaits = forfaits;
	}

	/**
	 * Getter du type de carte
	 * @return String typecarte
	 */
	public String getTypecarte() 
	{
		return typecarte;
	}

	/**
	 * Setter du type de carte
	 * @param typeCarte : le nouveau type de carte
	 */
	public void setTypecarte(String typeCarte)
	{
		this.typecarte = typeCarte;
	}

	/**
	 * Getter du numero de carte
	 * @return long numerocarte
	 */
	public long getNumerocarte() 
	{
		return numerocarte;
	}

	/**
	 * Setter du numero de carte
	 * @param numeroCarte : le nouveau numero de carte
	 */
	public void setNumerocarte(long numeroCarte) 
	{
		this.numerocarte = numeroCarte;
	}

	/**
	 * Getter de la date d'expiration
	 * @return Date dateexpiration
	 */
	public Date getDateexpiration() 
	{
		return dateexpiration;
	}

	/**
	 * Setter de la date d'expiration
	 * @param dateExpiration : la nouvelle date d'expiration
	 */
	public void setDateexpiration(Date dateExpiration) 
	{
		this.dateexpiration = dateExpiration;
	}

	/**
	 * Getter des copies
	 * @return Set<Object> copieses
	 */
	public Set<Object> getCopieses()
	{
		return copieses;
	}

	/**
	 * Setter des copies
	 * @param copieses : les nouvelles copies loue
	 */
	public void setCopieses(Set<Object> copies)
	{
		this.copieses = copies;
	}

}
