package Model;
// Generated Nov 30, 2018 9:19:15 AM by Hibernate Tools 5.3.6.Final

/**
 * ClientsId generated by hbm2java
 */
public class ClientsId implements java.io.Serializable {

	private static final long serialVersionUID = 813224666662760069L;
	
	/**
	 * L'utilisateur correspondant au client
	 */
	private Utilisateurs utilisateurs;

	/**
	 * Constructeur par defaut
	 */
	public ClientsId() 
	{
	}

	/**
	 * Construit l'id d'un client avec l'utilisateur correspondant
	 * @param utilisateur : l'utilisateur
	 */
	public ClientsId(Utilisateurs utilisateur) 
	{
		this.utilisateurs = utilisateur;
	}

	/**
	 * Getter de l'utilisateur
	 * @return Utilisateurs utilisateurs
	 */
	public Utilisateurs getUtilisateurs()
	{
		return utilisateurs;
	}

	/**
	 * Setter de l'utilisateur
	 * @param utilisateur : le nouvel utilisateur
	 */
	public void setUtilisateurs(Utilisateurs utilisateur)
	{
		this.utilisateurs = utilisateur;
	}

	/**
	 * Verifie si le client existe deja
	 */
	public boolean equals(Object other) 
	{
		if (this == other)
		{
			return true;
		}
		if (other == null)
		{
			return false;
		}
		if (!(other instanceof ClientsId))
		{
			return false;
		}
		
		ClientsId castOther = (ClientsId) other;

		return ((this.getUtilisateurs() == castOther.getUtilisateurs()) || (this.getUtilisateurs() != null && castOther.getUtilisateurs() != null && this.getUtilisateurs().equals(castOther.getUtilisateurs())));
	}

	/**
	 * Retourne l'utilisateur hache
	 */
	public int hashCode() 
	{
		int result = 17;

		result = 37 * result + (getUtilisateurs() == null ? 0 : this.getUtilisateurs().hashCode());
		return result;
	}

}
