package Model;
// Generated Nov 30, 2018 9:19:15 AM by Hibernate Tools 5.3.6.Final

/**
 * ClientsId generated by hbm2java
 */
public class ClientsId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 813224666662760069L;
	private Utilisateurs utilisateurs;

	public ClientsId() {
	}

	public ClientsId(Utilisateurs utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

	public Utilisateurs getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Utilisateurs utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClientsId))
			return false;
		ClientsId castOther = (ClientsId) other;

		return ((this.getUtilisateurs() == castOther.getUtilisateurs()) || (this.getUtilisateurs() != null
				&& castOther.getUtilisateurs() != null && this.getUtilisateurs().equals(castOther.getUtilisateurs())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUtilisateurs() == null ? 0 : this.getUtilisateurs().hashCode());
		return result;
	}

}
