package Model;
// Generated Nov 30, 2018 9:19:15 AM by Hibernate Tools 5.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Clients generated by hbm2java
 */
public class Clients implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 172434504324018254L;
	private ClientsId id;
	private Forfaits forfaits;
	private String typecarte;
	private long numerocarte;
	private Date dateexpiration;
	private Set copieses = new HashSet(0);

	public Clients() {
	}

	public Clients(ClientsId id, Forfaits forfaits, String typecarte, long numerocarte, Date dateexpiration) {
		this.id = id;
		this.forfaits = forfaits;
		this.typecarte = typecarte;
		this.numerocarte = numerocarte;
		this.dateexpiration = dateexpiration;
	}

	public Clients(ClientsId id, Forfaits forfaits, String typecarte, long numerocarte, Date dateexpiration,
			Set copieses) {
		this.id = id;
		this.forfaits = forfaits;
		this.typecarte = typecarte;
		this.numerocarte = numerocarte;
		this.dateexpiration = dateexpiration;
		this.copieses = copieses;
	}

	public ClientsId getId() {
		return this.id;
	}

	public void setId(ClientsId id) {
		this.id = id;
	}

	public Forfaits getForfaits() {
		return this.forfaits;
	}

	public void setForfaits(Forfaits forfaits) {
		this.forfaits = forfaits;
	}

	public String getTypecarte() {
		return this.typecarte;
	}

	public void setTypecarte(String typecarte) {
		this.typecarte = typecarte;
	}

	public long getNumerocarte() {
		return this.numerocarte;
	}

	public void setNumerocarte(long numerocarte) {
		this.numerocarte = numerocarte;
	}

	public Date getDateexpiration() {
		return this.dateexpiration;
	}

	public void setDateexpiration(Date dateexpiration) {
		this.dateexpiration = dateexpiration;
	}

	public Set getCopieses() {
		return this.copieses;
	}

	public void setCopieses(Set copieses) {
		this.copieses = copieses;
	}

}
