package Model;

import java.util.Date;

// Generated Nov 30, 2018 9:19:15 AM by Hibernate Tools 5.3.6.Final

/**
 * Copies generated by hbm2java
 */
public class Copies implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4582693674896808117L;
	private int numerocopie;
	private Films films;
	private Clients clients;
	private Date dateLocation;

	public Copies() {
	}

	public Copies(int numerocopie, Films films) {
		this.numerocopie = numerocopie;
		this.films = films;
	}

	public Copies(int numerocopie, Films films, Clients clients) {
		this.numerocopie = numerocopie;
		this.films = films;
		this.clients = clients;
	}
	
	public Date getDateLocation() {
		return dateLocation;
	}

	public void setDateLocation(Date dateLocation) {
		this.dateLocation = dateLocation;
	}

	public int getNumerocopie() {
		return this.numerocopie;
	}

	public void setNumerocopie(int numerocopie) {
		this.numerocopie = numerocopie;
	}

	public Films getFilms() {
		return this.films;
	}

	public void setFilms(Films films) {
		this.films = films;
	}

	public Clients getClients() {
		return this.clients;
	}

	public void setClients(Clients clients) {
		this.clients = clients;
	}

}
