package Model;

import java.util.Date;

// Generated Nov 30, 2018 9:19:15 AM by Hibernate Tools 5.3.6.Final

/**
 * Copies generated by hbm2java
 */
public class Copies implements java.io.Serializable {

	private static final long serialVersionUID = -4582693674896808117L;
	
	/**
	 * Attributs de la classe correspondant aux champs de la table
	 */
	private int numerocopie;
	private Films films;
	private Clients clients;
	private Date datelocation;

	/**
	 * Constructeur par defaut
	 */
	public Copies() 
	{
	}

	/**
	 * Construit une copie avec son numero et le film correspondant
	 * @param numeroCopie : le numero de la copie
	 * @param films : le film correspondant
	 */
	public Copies(int numeroCopie, Films film)
	{
		this.numerocopie = numeroCopie;
		this.films = film;
	}

	/**
	 * Construit une copie avec son numero et le film correspondant et son locataire
	* @param numeroCopie : le numero de la copie
	 * @param films : le film correspondant
	 * @param client : le locataire
	 */
	public Copies(int numeroCopie, Films film, Clients client)
	{
		this.numerocopie = numeroCopie;
		this.films = film;
		this.clients = client;
	}
	
	/**
	 * Getter de la date de location
	 * @return Date dateLocation
	 */
	public Date getDatelocation() 
	{
		return datelocation;
	}

	/**
	 * Setter de la date de location
	 * @param dateLocation : la nouvelle date de location
	 */
	public void setDatelocation(Date datelocation) 
	{
		this.datelocation = datelocation;
	}

	/**
	 * Getter du numero de la copie
	 * @return int numerocopie
	 */
	public int getNumerocopie()
	{
		return numerocopie;
	}

	/**
	 * Setter du numero de la copie
	 * @param numeroCopie : le nouveau numero de la copie
	 */
	public void setNumerocopie(int numeroCopie)
	{
		this.numerocopie = numeroCopie;
	}

	/**
	 * Getter du film correspondant
	 * @return Films films
	 */
	public Films getFilms()
	{
		return films;
	}

	/**
	 * Setter du film
	 * @param film : le nouveau film
	 */
	public void setFilms(Films film) 
	{
		this.films = film;
	}

	/**
	 * Getter du locataire
	 * @return Clients clients
	 */
	public Clients getClients() 
	{
		return this.clients;
	}

	/**
	 * Setter du client
	 * @param client : le nouveau client
	 */
	public void setClients(Clients client)
	{
		this.clients = client;
	}

}
