package Model;
// Generated Nov 30, 2018 9:19:15 AM by Hibernate Tools 5.3.6.Final

/**
 * Employes generated by hbm2java
 */
public class Employes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6023839981956432730L;
	private int matricule;
	private Utilisateurs utilisateurs;

	public Employes() {
	}

	public Employes(int matricule, Utilisateurs utilisateurs) {
		System.out.println("Nouvel employe, matricule : " + matricule);
		this.matricule = matricule;
		this.utilisateurs = utilisateurs;
	}

	public int getMatricule() {
		return this.matricule;
	}

	public void setMatricule(int matricule) {
		this.matricule = matricule;
	}

	public Utilisateurs getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Utilisateurs utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

}
