package Model;
// Generated Nov 30, 2018 9:19:15 AM by Hibernate Tools 5.3.6.Final

/**
 * Employes generated by hbm2java
 */
public class Employes {

	//private static final long serialVersionUID = 6023839981956432730L;
	
	/**
	 * Attributs de la classe correspondant aux champs de la table
	 */
	private int matricule;
	private Utilisateurs utilisateurs;

	/**
	 * Constructeur par defaut
	 */
	public Employes() 
	{
	}

	/**
	 * Construit un employe avec son matricule et l'utilisateur correspondant
	 * @param matricule : le matricule de l'employe
	 * @param utilisateurs : l'utilisateur correspondant
	 */
	public Employes(int matricule, Utilisateurs utilisateur) 
	{
		this.matricule = matricule;
		this.utilisateurs = utilisateur;
	}

	/**
	 * Getter du matricule
	 * @return int matricule
	 */
	public int getMatricule() 
	{
		return matricule;
	}

	/**
	 * Setter du matricule
	 * @param matricule : le nouveau matricule
	 */
	public void setMatricule(int matricule)
	{
		this.matricule = matricule;
	}

	/**
	 * Getter de l'utilisateur
	 * @return Utilisateurs utilisateurs
	 */
	public Utilisateurs getUtilisateurs() 
	{
		return utilisateurs;
	}

	/**
	 * Setter de l'utilisateur
	 * @param utilisateur : le nouvel utilisateur
	 */
	public void setUtilisateurs(Utilisateurs utilisateur)
	{
		this.utilisateurs = utilisateur;
	}

}
