package Model;
// Generated Nov 30, 2018 9:19:15 AM by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Films generated by hbm2java
 */
public class Films implements java.io.Serializable {

	private static final long serialVersionUID = 1694271170317920677L;
	private String titre;
	private int annee;
	private short duree;
	private String langue;
	private String resume;
	private String genres;
	private String paysproduction;
	private Set<Object> rolesacteurses = new HashSet<Object>(0);
	private Set<Object> personneses = new HashSet<Object>(0); // scenaristes
	private Set<Object> copieses = new HashSet<Object>(0);

	public Films() {
	}

	public Films(String titre, int annee, short duree, String langue, String resume, String genres,
			String paysproduction) {
		this.titre = titre;
		this.annee = annee;
		this.duree = duree;
		this.langue = langue;
		this.resume = resume;
		this.genres = genres;
		this.paysproduction = paysproduction;
	}

	public Films(String titre, int annee, short duree, String langue, String resume, String genres,
			String paysproduction, Set<Object> rolesacteurses, Set<Object> personneses, Set<Object> copieses) {
		this.titre = titre;
		this.annee = annee;
		this.duree = duree;
		this.langue = langue;
		this.resume = resume;
		this.genres = genres;
		this.paysproduction = paysproduction;
		this.rolesacteurses = rolesacteurses;
		this.personneses = personneses;
		this.copieses = copieses;
	}


	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	public int getAnnee() {
		return this.annee;
	}

	public void setAnnee(int annee) {
		this.annee = annee;
	}

	public short getDuree() {
		return this.duree;
	}

	public void setDuree(short duree) {
		this.duree = duree;
	}

	public String getLangue() {
		return this.langue;
	}

	public void setLangue(String langue) {
		this.langue = langue;
	}

	public String getResume() {
		return this.resume;
	}

	public void setResume(String resume) {
		this.resume = resume;
	}

	public String getGenres() {
		return this.genres;
	}

	public void setGenres(String genres) {
		this.genres = genres;
	}

	public String getPaysproduction() {
		return this.paysproduction;
	}

	public void setPaysproduction(String paysproduction) {
		this.paysproduction = paysproduction;
	}

	public Set<Object> getRolesacteurses() {
		return this.rolesacteurses;
	}

	public void setRolesacteurses(Set<Object> rolesacteurses) {
		this.rolesacteurses = rolesacteurses;
	}

	public Set<Object> getPersonneses() {
		return this.personneses;
	}

	public void setPersonneses(Set<Object> personneses) {
		this.personneses = personneses;
	}

	public Set<Object> getCopieses() {
		return this.copieses;
	}

	public void setCopieses(Set<Object> copieses) {
		this.copieses = copieses;
	}

}
