package Model;
// Generated Nov 30, 2018 9:19:15 AM by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Forfaits generated by hbm2java
 */
public class Forfaits implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3324040119877310711L;
	private String typeforfait;
	private double cout;
	private byte locationmax;
	private short dureemax;
	private Set<Object> clientses = new HashSet<Object>(0);

	public Forfaits() {
	}

	public Forfaits(String typeforfait, double cout, byte locationmax, short dureemax) {
		this.typeforfait = typeforfait;
		this.cout = cout;
		this.locationmax = locationmax;
		this.dureemax = dureemax;
	}

	public Forfaits(String typeforfait, double cout, byte locationmax, short dureemax, Set<Object> clientses) {
		this.typeforfait = typeforfait;
		this.cout = cout;
		this.locationmax = locationmax;
		this.dureemax = dureemax;
		this.clientses = clientses;
	}

	public String getTypeforfait() {
		return this.typeforfait;
	}

	public void setTypeforfait(String typeforfait) {
		this.typeforfait = typeforfait;
	}

	public double getCout() {
		return this.cout;
	}

	public void setCout(double cout) {
		this.cout = cout;
	}

	public byte getLocationmax() {
		return this.locationmax;
	}

	public void setLocationmax(byte locationmax) {
		this.locationmax = locationmax;
	}

	public short getDureemax() {
		return this.dureemax;
	}

	public void setDureemax(short dureemax) {
		this.dureemax = dureemax;
	}

	public Set<Object> getClientses() {
		return this.clientses;
	}

	public void setClientses(Set<Object> clientses) {
		this.clientses = clientses;
	}

}
