package Model;
// Generated Nov 30, 2018 9:19:15 AM by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Forfaits generated by hbm2java
 */
public class Forfaits {

	
	/**
	 * Attributs de la classe correspondant aux champs de la table
	 */
	private String typeforfait;
	private double cout;
	private byte locationmax;
	private short dureemax;
	
	/**
	 * Liste des clients qui ont ce forfait
	 */
	private Set<Object> clientses = new HashSet<Object>(0);

	/**
	 * Constructeur par defaut
	 */
	public Forfaits() 
	{
	}

	/**
	 * Construit un forfait avec tous ses attributs
	 * @param typeForfait : le type du forfait
	 * @param cout : le cout du forfait
	 * @param locationMax : le nombre de location maximal du forfait
	 * @param dureeMax : la duree de location maximal du forfait
	 */
	public Forfaits(String typeForfait, double cout, byte locationMax, short dureeMax)
	{
		this.typeforfait = typeForfait;
		this.cout = cout;
		this.locationmax = locationMax;
		this.dureemax = dureeMax;
	}

	/**
	* Construit un forfait avec tous ses attributs et les clients qui vont avec
	 * @param typeForfait : le type du forfait
	 * @param cout : le cout du forfait
	 * @param locationMax : le nombre de location maximal du forfait
	 * @param dureeMax : la duree de location maximal du forfait
	 * @param clients : les clients qui ont ce forfait
	 */
	public Forfaits(String typeForfait, double cout, byte locationMax, short dureeMax, Set<Object> clients) 
	{
		this.typeforfait = typeForfait;
		this.cout = cout;
		this.locationmax = locationMax;
		this.dureemax = dureeMax;
		this.clientses = clients;
	}

	/**
	 * Getter du type
	 * @return String typeforfait
	 */
	public String getTypeforfait() 
	{
		return typeforfait;
	}

	/**
	 * Setter du type
	 * @param typeForfait : le nouveau type
	 */
	public void setTypeforfait(String typeForfait)
	{
		this.typeforfait = typeForfait;
	}

	/**
	 * Getter du cout
	 * @return double cout
	 */
	public double getCout() 
	{
		return cout;
	}

	/**
	 * Setter du cout
	 * @param cout : le nouveau cout
	 */
	public void setCout(double cout) 
	{
		this.cout = cout;
	}

	/**
	 * Getter du nombre de location maximal
	 * @return byte locationmax
	 */
	public byte getLocationmax()
	{
		return locationmax;
	}

	/**
	 * Setter du nombre de location maximal
	 * @param locationMax : le nouveau nombre de location maximal
	 */
	public void setLocationmax(byte locationMax) {
		this.locationmax = locationMax;
	}

	/**
	 * Getter de la duree maximal de location
	 * @return dureemax
	 */
	public short getDureemax()
	{
		return dureemax;
	}

	/**
	 * Setter de la duree maximal de location
	 * @param dureeMax : la nouvelle duree maximal
	 */
	public void setDureemax(short dureeMax)
	{
		this.dureemax = dureeMax;
	}

	/**
	 * Setter des clients
	 * @return Set<Object> clientses
	 */
	public Set<Object> getClientses() 
	{
		return clientses;
	}

	/**
	 * Setter des clients
	 * @param clients : les nouveaux clients
	 */
	public void setClientses(Set<Object> clients) {
		this.clientses = clients;
	}

}
