package Model;
// Generated Nov 30, 2018 9:19:15 AM by Hibernate Tools 5.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Personnes generated by hbm2java
 */
public class Personnes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5505318989705768740L;
	private PersonnesId id;
	private Date naissance;
	private String lieunaissance;
	private String biographie;
	private Set rolesacteurses = new HashSet(0);
	private Set filmses = new HashSet(0);

	public Personnes() {
	}

	public Personnes(PersonnesId id, Date naissance, String lieunaissance, String biographie) {
		this.id = id;
		this.naissance = naissance;
		this.lieunaissance = lieunaissance;
		this.biographie = biographie;
	}

	public Personnes(PersonnesId id, Date naissance, String lieunaissance, String biographie, Set rolesacteurses,
			Set filmses) {
		this.id = id;
		this.naissance = naissance;
		this.lieunaissance = lieunaissance;
		this.biographie = biographie;
		this.rolesacteurses = rolesacteurses;
		this.filmses = filmses;
	}

	public PersonnesId getId() {
		return this.id;
	}

	public void setId(PersonnesId id) {
		this.id = id;
	}

	public Date getNaissance() {
		return this.naissance;
	}

	public void setNaissance(Date naissance) {
		this.naissance = naissance;
	}

	public String getLieunaissance() {
		return this.lieunaissance;
	}

	public void setLieunaissance(String lieunaissance) {
		this.lieunaissance = lieunaissance;
	}

	public String getBiographie() {
		return this.biographie;
	}

	public void setBiographie(String biographie) {
		this.biographie = biographie;
	}

	public Set getRolesacteurses() {
		return this.rolesacteurses;
	}

	public void setRolesacteurses(Set rolesacteurses) {
		this.rolesacteurses = rolesacteurses;
	}

	public Set getFilmses() {
		return this.filmses;
	}

	public void setFilmses(Set filmses) {
		this.filmses = filmses;
	}

}
