package Model;
// Generated Nov 30, 2018 9:19:15 AM by Hibernate Tools 5.3.6.Final

/**
 * PersonnesId generated by hbm2java
 */
public class PersonnesId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4062482694929820178L;
	private String nom;
	private String prenom;

	public PersonnesId() {
	}

	public PersonnesId(String nom, String prenom) {
		this.nom = nom;
		this.prenom = prenom;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PersonnesId))
			return false;
		PersonnesId castOther = (PersonnesId) other;

		return ((this.getNom() == castOther.getNom())
				|| (this.getNom() != null && castOther.getNom() != null && this.getNom().equals(castOther.getNom())))
				&& ((this.getPrenom() == castOther.getPrenom()) || (this.getPrenom() != null
						&& castOther.getPrenom() != null && this.getPrenom().equals(castOther.getPrenom())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNom() == null ? 0 : this.getNom().hashCode());
		result = 37 * result + (getPrenom() == null ? 0 : this.getPrenom().hashCode());
		return result;
	}

}
