package Model;
// Generated Nov 30, 2018 9:19:15 AM by Hibernate Tools 5.3.6.Final

/**
 * RolesacteursId generated by hbm2java
 */
public class RolesacteursId implements java.io.Serializable {

	private static final long serialVersionUID = -1755631568107139769L;
	
	/**
	 * Attributs de la classe correspondant aux champs de la table
	 */
	private Personnes personnes;
	private Films films;

	/**
	 * Constructeur par defaut
	 */
	public RolesacteursId() 
	{
	}

	/**
	 * Construit l'id d'un acteur avec la personne et le film correspondants
	 * @param personne : la personne correspondante
	 * @param film : le film correspondant
	 */
	public RolesacteursId(Personnes personne, Films film)
	{
		this.personnes = personne;
		this.films = film;
	}

	/**
	 * Getter de la personne
	 * @return Personnes personnes
	 */
	public Personnes getPersonnes()
	{
		return personnes;
	}

	/**
	 * Setter de la personne
	 * @param personne : la nouvelle personne
	 */
	public void setPersonnes(Personnes personne) 
	{
		this.personnes = personne;
	}

	/**
	 * Getter du film
	 * @return Films films
	 */
	public Films getFilms()
	{
		return films;
	}

	/**
	 * Setter du film
	 * @param film : le nouveau film
	 */
	public void setFilms(Films film) 
	{
		this.films = film;
	}

	/**
	 * Verifie si l'acteur existe deja
	 */
	public boolean equals(Object other)
	{
		if (this == other)
		{
			return true;
		}
		if (other == null)
		{
			return false;
		}
		if (!(other instanceof RolesacteursId))
		{
			return false;
		}
		
		RolesacteursId castOther = (RolesacteursId) other;

		return ((this.getPersonnes() == castOther.getPersonnes()) || (this.getPersonnes() != null && castOther.getPersonnes() != null && this.getPersonnes().equals(castOther.getPersonnes()))) && ((this.getFilms() == castOther.getFilms()) || (this.getFilms() != null && castOther.getFilms() != null && this.getFilms().equals(castOther.getFilms())));
	}

	/**
	 * Retourne l'acteur hache
	 */
	public int hashCode()
	{
		int result = 17;

		result = 37 * result + (getPersonnes() == null ? 0 : this.getPersonnes().hashCode());
		result = 37 * result + (getFilms() == null ? 0 : this.getFilms().hashCode());
		return result;
	}

}
