package Model;
// Generated Nov 30, 2018 9:19:15 AM by Hibernate Tools 5.3.6.Final

/**
 * RolesacteursId generated by hbm2java
 */
public class RolesacteursId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1755631568107139769L;
	private Personnes personnes;
	private Films films;

	public RolesacteursId() {
	}

	public RolesacteursId(Personnes personnes, Films films) {
		this.personnes = personnes;
		this.films = films;
	}

	public Personnes getPersonnes() {
		return this.personnes;
	}

	public void setPersonnes(Personnes personnes) {
		this.personnes = personnes;
	}

	public Films getFilms() {
		return this.films;
	}

	public void setFilms(Films films) {
		this.films = films;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RolesacteursId))
			return false;
		RolesacteursId castOther = (RolesacteursId) other;

		return ((this.getPersonnes() == castOther.getPersonnes()) || (this.getPersonnes() != null
				&& castOther.getPersonnes() != null && this.getPersonnes().equals(castOther.getPersonnes())))
				&& ((this.getFilms() == castOther.getFilms()) || (this.getFilms() != null
						&& castOther.getFilms() != null && this.getFilms().equals(castOther.getFilms())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPersonnes() == null ? 0 : this.getPersonnes().hashCode());
		result = 37 * result + (getFilms() == null ? 0 : this.getFilms().hashCode());
		return result;
	}

}
