package Model;
// Generated Nov 30, 2018 9:19:15 AM by Hibernate Tools 5.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Utilisateurs generated by hbm2java
 */
public class Utilisateurs implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4708408073187867370L;
	private UtilisateursId id;
	private String courriel;
	private String telephone;
	private Date naissance;
	private String motdepasse;
	private String adresse;
	private Set<Object> employeses = new HashSet<Object>(0);
	private Clients clients;

	public Utilisateurs() {
	}

	public Utilisateurs(UtilisateursId id, String courriel, String telephone, Date naissance, String motdepasse,
			String adresse) {
		this.id = id;
		this.courriel = courriel;
		this.telephone = telephone;
		this.naissance = naissance;
		this.motdepasse = motdepasse;
		this.adresse = adresse;
		System.out.println("Nouvel utilisateur : " + id.getNom() + " " + id.getPrenom());
	}

	public Utilisateurs(UtilisateursId id, String courriel, String telephone, Date naissance, String motdepasse,
			String adresse, Set<Object> employeses, Clients clients) {
		this.id = id;
		this.courriel = courriel;
		this.telephone = telephone;
		this.naissance = naissance;
		this.motdepasse = motdepasse;
		this.adresse = adresse;
		this.employeses = employeses;
		this.clients = clients;
	}

	public UtilisateursId getId() {
		return this.id;
	}

	public void setId(UtilisateursId id) {
		this.id = id;
	}

	public String getCourriel() {
		return this.courriel;
	}

	public void setCourriel(String courriel) {
		this.courriel = courriel;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public Date getNaissance() {
		return this.naissance;
	}

	public void setNaissance(Date naissance) {
		this.naissance = naissance;
	}

	public String getMotdepasse() {
		return this.motdepasse;
	}

	public void setMotdepasse(String motdepasse) {
		this.motdepasse = motdepasse;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	public Set<Object> getEmployeses() {
		return this.employeses;
	}

	public void setEmployeses(Set<Object> employeses) {
		this.employeses = employeses;
	}

	public Clients getClients() {
		return this.clients;
	}

	public void setClients(Clients clients) {
		this.clients = clients;
	}

}
