package Model;
// Generated Nov 30, 2018 9:19:15 AM by Hibernate Tools 5.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Utilisateurs generated by hbm2java
 */
public class Utilisateurs implements java.io.Serializable {

	private static final long serialVersionUID = 4708408073187867370L;
	
	/**
	 * Attributs de la classe correspondant aux champs de la table
	 */
	private UtilisateursId id;
	private String courriel;
	private String telephone;
	private Date naissance;
	private String motdepasse;
	private String adresse;
	
	/**
	 * Liste des employes
	 */
	private Set<Object> employeses = new HashSet<Object>(0);
	
	/**
	 * Le client
	 */
	private Clients clients;

	/**
	 * Constructeur par defaut
	 */
	public Utilisateurs()
	{
	}

	/**
	 * Construit un utilisateur avec ses attributs
	 * @param id : l'id de l'utilisateur
	 * @param courriel : le courriel de l'utilisateur
	 * @param telephone : le telephone de l'utilisateur
	 * @param naissance : la date de naissance de l'utilisateur
	 * @param motDePasse : le mot de passe de l'utilisateur
	 * @param adresse : l'adresse de l'utilisateur
	 */
	public Utilisateurs(UtilisateursId id, String courriel, String telephone, Date naissance, String motDePasse, String adresse)
	{
		this.id = id;
		this.courriel = courriel;
		this.telephone = telephone;
		this.naissance = naissance;
		this.motdepasse = motDePasse;
		this.adresse = adresse;
	}

	/**
	 * Construit un utilisateur avec ses attributs
	 * @param id : l'id de l'utilisateur
	 * @param courriel : le courriel de l'utilisateur
	 * @param telephone : le telephone de l'utilisateur
	 * @param naissance : la date de naissance de l'utilisateur
	 * @param motDePasse : le mot de passe de l'utilisateur
	 * @param adresse : l'adresse de l'utilisateur
	 * @param employes : les employes associes
	 * @param client : le client associes
	 */
	public Utilisateurs(UtilisateursId id, String courriel, String telephone, Date naissance, String motDePasse, String adresse, Set<Object> employes, Clients client)
	{
		this.id = id;
		this.courriel = courriel;
		this.telephone = telephone;
		this.naissance = naissance;
		this.motdepasse = motDePasse;
		this.adresse = adresse;
		this.employeses = employes;
		this.clients = client;
	}

	/**
	 * Getter de l'id
	 * @return UtilisateursId id
	 */
	public UtilisateursId getId()
	{
		return id;
	}

	/**
	 * Setter de l'id
	 * @param id : le nouvel id
	 */
	public void setId(UtilisateursId id)
	{
		this.id = id;
	}

	/**
	 * Getter du courriel
	 * @return String courriel
	 */
	public String getCourriel()
	{
		return courriel;
	}

	/**
	 * Setter du courriel
	 * @param courriel : le nouveau courriel
	 */
	public void setCourriel(String courriel)
	{
		this.courriel = courriel;
	}

	/**
	 * Getter du numero de telephone
	 * @return String telephone
	 */
	public String getTelephone() 
	{
		return telephone;
	}

	/**
	 * Setter du numero de telephone
	 * @param telephone : le nouveau numero
	 */
	public void setTelephone(String telephone)
	{
		this.telephone = telephone;
	}

	/**
	 * Getter de la date de naissance
	 * @return Date naissance
	 */
	public Date getNaissance()
	{
		return naissance;
	}

	/**
	 * Setter de la date de naissance
	 * @param naissance : la nouvelle date
	 */
	public void setNaissance(Date naissance)
	{
		this.naissance = naissance;
	}

	/**
	 * Getter du mot de passe
	 * @return String motdepasse
	 */
	public String getMotdepasse()
	{
		return motdepasse;
	}

	/**
	 * Setter du mot de passe
	 * @param motDePasse
	 */
	public void setMotdepasse(String motDePasse) 
	{
		this.motdepasse = motDePasse;
	}

	/**
	 * Getter de l'adresse
	 * @return String adresse
	 */
	public String getAdresse()
	{
		return adresse;
	}

	/**
	 * Setter de l'adresse
	 * @param adresse : le nouvelle adresse
	 */
	public void setAdresse(String adresse)
	{
		this.adresse = adresse;
	}

	/**
	 * Getter des employes
	 * @return Set<Object> employeses
	 */
	public Set<Object> getEmployeses()
	{
		return employeses;
	}

	/**
	 * Setter des employes
	 * @param employes : les nouveaux employes
	 */
	public void setEmployeses(Set<Object> employes) 
	{
		this.employeses = employes;
	}

	/**
	 * Getter du client
	 * @return Clients clients
	 */
	public Clients getClients()
	{
		return clients;
	}

	/**
	 * Setter du client
	 * @param client : le nouveau client
	 */
	public void setClients(Clients client)
	{
		this.clients = client;
	}

}
