package Model;
// Generated Nov 30, 2018 9:19:15 AM by Hibernate Tools 5.3.6.Final

/**
 * UtilisateursId generated by hbm2java
 */
public class UtilisateursId implements java.io.Serializable {

	private static final long serialVersionUID = -5815487541207129370L;
	
	/**
	 * Attributs de la classe correspondant aux champs de la table
	 */
	private String nom;
	private String prenom;

	/**
	 * Constructeur par defaut
	 */
	public UtilisateursId() 
	{
	}

	/**
	 * Construit l'id d'un utilisateur avec ses attributs
	 * @param nom : le nom de l'utilisateur
	 * @param prenom : le prenom de l'utilisateur
	 */
	public UtilisateursId(String nom, String prenom)
	{
		this.nom = nom;
		this.prenom = prenom;
	}

	/**
	 * Getter du nom
	 * @return String nom
	 */
	public String getNom() 
	{
		return nom;
	}

	/**
	 * Setter du nom
	 * @param nom : le nouveau nom
	 */
	public void setNom(String nom)
	{
		this.nom = nom;
	}

	/**
	 * Getter du prenom
	 * @return String prenom
	 */
	public String getPrenom()
	{
		return prenom;
	}

	/**
	 * Setter du prenom
	 * @param prenom
	 */
	public void setPrenom(String prenom) 
	{
		this.prenom = prenom;
	}

	/**
	 * Verifie si l'acteur existe deja
	 */
	public boolean equals(Object other)
	{
		if (this == other)
		{
			return true;
		}
		if (other == null)
		{
			return false;
		}
		if (!(other instanceof UtilisateursId))
		{
			return false;
		}
		
		UtilisateursId castOther = (UtilisateursId) other;

		return ((this.getNom() == castOther.getNom()) || (this.getNom() != null && castOther.getNom() != null && this.getNom().equals(castOther.getNom()))) && ((this.getPrenom() == castOther.getPrenom()) || (this.getPrenom() != null && castOther.getPrenom() != null && this.getPrenom().equals(castOther.getPrenom())));
	}

	/**
	 * Retourne l'acteur hache
	 */
	public int hashCode()
	{
		int result = 17;

		result = 37 * result + (getNom() == null ? 0 : this.getNom().hashCode());
		result = 37 * result + (getPrenom() == null ? 0 : this.getPrenom().hashCode());
		return result;
	}

}
